# Generated by Django 2.2.19 on 2021-03-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='final_docfile',
            field=models.FileField(default='abc', upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(default='abc', upload_to='documents/%Y/%m/%d'),
        ),
    ]
