# Generated by Django 2.2.19 on 2021-03-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210325_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='document',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
